version: '3.8'

services:
  web:
    image: ruilobos/bakery-a-web:latest
    command: sh -c "python manage.py migrate && gunicorn bakery.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "9001:8000"
    environment:
      DATABASE_URL: postgres://postgres:r1l2_postgre@simple:5432/simple
    restart: always