# Generated by Django 3.2 on 2021-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_remove_recipe_ingredients_base_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('recipe_yeld', models.IntegerField(verbose_name='Recipe Yield')),
                ('yield_unit', models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNIT', 'unit')], max_length=5, verbose_name='Yield Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Selling Price (€)')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='VAT (%)')),
                ('ingredients', models.ManyToManyField(blank=True, to='control.Recipe_Ingredients')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
