# Generated by Django 3.2 on 2021-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('BEVERAGEs', 'Beverages'), ('CAKES', 'Cakes'), ('DESSERTS', 'Desserts'), ('FINANCIER & MADELEINE', 'Financier & Madeleine'), ('FRENCH TOASTS', 'French Toasts'), ('HOT FOODS', 'Hot Foods'), ('MACARONS', 'Macarons'), ('PASTRIES', 'Pastries'), ('SANDWICHES', 'Sandwiches'), ('SCONE, CREPE & PORRIDGE', 'Scone, Crepe & Porridge'), ('SWEETS', 'Sweets')], default=222, max_length=30, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_yeld',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Recipe Yield'),
        ),
    ]
