# Generated by Django 3.2 on 2021-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20210418_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('BEVERAGES', 'Beverages'), ('CAKES', 'Cakes'), ('DESSERTS', 'Desserts'), ('FINANCIER & MADELEINE', 'Financier & Madeleine'), ('FRENCH TOASTS', 'French Toasts'), ('HOT FOODS', 'Hot Foods'), ('MACARONS', 'Macarons'), ('PASTRIES', 'Pastries'), ('SANDWICHES', 'Sandwiches'), ('SCONE, CREPE & PORRIDGE', 'Scone, Crepe & Porridge'), ('SWEETS', 'Sweets')], max_length=30, verbose_name='Category'),
        ),
    ]
