# Generated by Django 3.2 on 2021-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20210421_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='control.Recipe_Ingredients'),
        ),
    ]
