# Generated by Django 3.2 on 2021-04-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_remove_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_recipes',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Bs_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNIT', 'unit')], max_length=5, verbose_name='Unit')),
                ('base_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.base_recipes')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.rawmaterial')),
            ],
            options={
                'verbose_name': 'Base Recipe Ingredient',
                'verbose_name_plural': 'Base Recipies Ingredients',
                'ordering': ['ingredient'],
            },
        ),
    ]
