# Generated by Django 3.2 on 2021-04-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Base Recipe Name')),
                ('recipe_yeld', models.IntegerField(verbose_name='Recipe Yield')),
                ('yield_unit', models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNIT', 'unit')], max_length=5, verbose_name='Yield Unit')),
            ],
            options={
                'verbose_name': 'Base Recipe',
                'verbose_name_plural': 'Base Recipes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.CharField(max_length=6, verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BEVERAGE', 'Beverage'), ('BREAD', 'Bread'), ('DAIRY & EGGS', 'Dairy & Eggs'), ('DRY GOODS', 'Dry Goods'), ('FISH', 'Fish'), ('FRUIT & VEG', 'Fruit & Veg'), ('MEAT', 'Meat'), ('PACKING', 'Packing')], max_length=30, verbose_name='Category')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNIT', 'unit')], max_length=5, verbose_name='Unit')),
                ('base_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.base_recipes')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.rawmaterial')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['ingredient'],
            },
        ),
        migrations.AddField(
            model_name='base_recipes',
            name='ingredients',
            field=models.ManyToManyField(to='control.Recipe_Ingredients'),
        ),
    ]
