# Generated by Django 3.2 on 2021-04-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_recipe_ingredients_base_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_ingredients',
            name='base_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.base_recipes'),
        ),
        migrations.AlterField(
            model_name='base_recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='control.Recipe_Ingredients'),
        ),
    ]
