# Generated by Django 3.2 on 2021-04-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20210418_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='base_recipe',
        ),
    ]
