# Generated by Django 3.2 on 2021-04-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_product_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe_ingredients',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.product'),
        ),
    ]
