# Generated by Django 3.2 on 2021-04-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
    ]
